### ISSUE TITLE
Button colors and position improvement

### ISSUE THREAD

**Issue by Iq5cMcGP91Og** [newtoallofthis123/NoobPaste#2]
I think since the favicon and logo has yellow colour having them match with buttons would look more better as a whole.

**Comment by Iq5cMcGP91Og** [comment]
#4 
![resim](https://user-images.githubusercontent.com/73298240/198996258-56955f87-e4ac-45d1-b8ad-d9ea7eb6e956.png)
![resim](https://user-images.githubusercontent.com/73298240/198996365-a493e286-0028-4037-9e30-daf028fa60dd.png)

**Comment by newtoallofthis123** [comment]
Looks Cool :) Thanks for the update
