### ISSUE TITLE
Navbar update

### ISSUE THREAD

**Issue by Iq5cMcGP91Og** [newtoallofthis123/NoobPaste#5]
From this:

![resim](https://user-images.githubusercontent.com/73298240/199879401-2a6de7e5-4037-4f75-970f-549fc0db12e2.png)

to this:

![resim](https://user-images.githubusercontent.com/73298240/199879497-06e54523-0cd0-42ac-912b-cd5baf4e5478.png)

Navbar is sticked to top, buttons are rounded with yellow colour. 
Only problem the avatar picture kinda breakes the height of them.

What do you think?

**Comment by newtoallofthis123** [comment]
Can we manipulate the gravatar url's api call to a more supported dimensions, like 480X480 or something like that.
Otherwise looks very cool

**Comment by newtoallofthis123** [comment]
Check the latest update, this issue is fixed
![firefox_YqG0NkdsQa](https://user-images.githubusercontent.com/78465651/200895592-22b1c543-c1ed-40ca-8388-e9fe7b3f19ea.png)
